name: Decompile dylib

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'dylib filename'
        required: true

jobs:
  decompile:
    runs-on: macos-latest  # macOS Runner を使用する
    steps:
      - name: ファイルをダウンロード
        run: curl -L -o "${{ github.event.inputs.filename }}" "https://raw.githubusercontent.com/rhgrive/build/main/${{ github.event.inputs.filename }}"

      - name: 逆アセンブル (otool)
        run: |
          otool -tv "${{ github.event.inputs.filename }}" > decompiled.txt
          strings "${{ github.event.inputs.filename }}" > strings.txt
          nm -g "${{ github.event.inputs.filename }}" > symbols.txt

      - name: 結果をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-files
          path: |
            decompiled.txt
            strings.txt
            symbols.txt
