name: Decompile dylib

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      filename:
        description: 'dylib filename'
        required: true

jobs:
  decompile:
    runs-on: macos-latest
    steps:
      - name: ファイル名を取得
        run: |
          if [[ -z "${{ github.event.inputs.filename }}" ]]; then
            FILENAME=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=filename: ).*' | tr -d '\r')
          else
            FILENAME="${{ github.event.inputs.filename }}"
          fi
          echo "FILENAME=${FILENAME}" >> $GITHUB_ENV

      - name: ファイルをダウンロード
        run: curl -L -o "$FILENAME" "https://raw.githubusercontent.com/rhgrive/build/main/$FILENAME"

      - name: 逆アセンブル (otool)
        run: |
          otool -tv "$FILENAME" > decompiled.txt
          strings "$FILENAME" > strings.txt
          nm -g "$FILENAME" > symbols.txt

      - name: 結果をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-files
          path: |
            decompiled.txt
            strings.txt
            symbols.txt
