name: Decompile dylib

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'dylib filename'
        required: true

jobs:
  decompile:
    runs-on: macos-latest  # macOS Runner を使用する
    steps:
      - name: ファイルをダウンロード
        run: curl -L -o target.dylib "https://raw.githubusercontent.com/rhgrive/build/main/target.dylib"

      - name: 逆アセンブル (otool)
        run: |
          otool -tv target.dylib > decompiled.txt
          strings target.dylib > strings.txt
          nm -g target.dylib > symbols.txt

      - name: 結果をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-files
          path: |
            decompiled.txt
            strings.txt
            symbols.txt
