name: Decompile dylib

on:
  issues:
    types: [opened]

jobs:
  decompile:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: 必要なツールをインストール
        run: |
          sudo apt update
          sudo apt install -y binutils clang llvm

      - name: dylib ファイルのダウンロード
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          URL=$(echo "$ISSUE_BODY" | grep -oP '(?<=URL: ).*')
          curl -L -o target.dylib "$URL"

      - name: 逆アセンブル
        run: |
          otool -tv target.dylib > decompiled.txt
          strings target.dylib > strings.txt
          nm -g target.dylib > symbols.txt

      - name: 結果をアップロード
        uses: actions/upload-artifact@v4
        with:
          name: decompiled-files
          path: |
            decompiled.txt
            strings.txt
            symbols.txt
